debug: true
spring:
  application:
    name: monitoring-engine
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/micropulse
    username: postgres
    password: micropulse
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8090

micropulse:
  targets:
    - name: auth-service
      base-url: http://localhost:8080
    - name: payment-service
      base-url: http://localhost:8081